package vista;

import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import vista.InvestigadorFrame;

/**
 *
 * @author danie
 */
public class AnalisisFrame extends javax.swing.JFrame {
    
    private int[][] matrizResultado;
    private int[][] matrizPatron;
    private JLabel[][] labelsResultado;
    private JLabel[][] labelsPatron;
    private InvestigadorFrame investigadorFrame;
    private String nombrePatron;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnalisisFrame.class.getName());

    public AnalisisFrame(int[][] matrizResultado, int[][] matrizPatron, InvestigadorFrame investigadorFrame, String nombrePatron) {
        initComponents();

        this.matrizResultado = matrizResultado;
        this.matrizPatron = matrizPatron;
        this.investigadorFrame = investigadorFrame;
        this.nombrePatron = nombrePatron;

        setTitle("Análisis en tiempo real");
        setSize(600, 400);
        setLocationRelativeTo(null);

        construirMatrices();
        iniciarAnalisis();
    }
    
    public AnalisisFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void construirMatrices() {
        javax.swing.JPanel panelPrincipal = new javax.swing.JPanel();
        panelPrincipal.setLayout(new java.awt.GridLayout(1, 2, 20, 20));
        
        javax.swing.JPanel panelResultado = new javax.swing.JPanel(new GridLayout(2, 2));
        javax.swing.JPanel panelPatron = new javax.swing.JPanel(new GridLayout(2, 2));

        labelsResultado = new JLabel[2][2];
        labelsPatron = new JLabel[2][2];

        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 2; j++) {
                labelsResultado[i][j] = crearCelda(matrizResultado[i][j]);
                labelsPatron[i][j] = crearCelda(matrizPatron[i][j]);

                panelResultado.add(labelsResultado[i][j]);
                panelPatron.add(labelsPatron[i][j]);
            }
        }

        javax.swing.JPanel contenedorResultado = new javax.swing.JPanel(new java.awt.BorderLayout());
        contenedorResultado.add(new javax.swing.JLabel("Matriz Resultante", SwingConstants.CENTER), java.awt.BorderLayout.NORTH);
        contenedorResultado.add(panelResultado, java.awt.BorderLayout.CENTER);

        javax.swing.JPanel contenedorPatron = new javax.swing.JPanel(new java.awt.BorderLayout());
        contenedorPatron.add(new javax.swing.JLabel("Matriz Patrón", SwingConstants.CENTER), java.awt.BorderLayout.NORTH);
        contenedorPatron.add(panelPatron, java.awt.BorderLayout.CENTER);
    
        panelPrincipal.add(contenedorResultado);
        panelPrincipal.add(contenedorPatron);

        setLayout(new java.awt.BorderLayout());
        getContentPane().removeAll();
        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);
        pack();
        revalidate();
        repaint();
    }
    
    private JLabel crearCelda(int valor) {
        JLabel label = new JLabel(String.valueOf(valor), SwingConstants.CENTER);
        label.setOpaque(true);
        label.setBackground(Color.LIGHT_GRAY);
        label.setForeground(Color.BLACK);
        label.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
        label.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
        return label;
    }
    
    private void iniciarAnalisis() {
        Thread hilo = new Thread(() -> {
            boolean coincide = true;

            for (int i = 0; i < 2; i++) {
                for (int j = 0; j < 2; j++) {

                    boolean celdaCoincide = matrizResultado[i][j] == matrizPatron[i][j];

                    int fila = i;
                    int columna = j;

                    SwingUtilities.invokeLater(() -> {
                        if (celdaCoincide) {
                            labelsResultado[fila][columna].setBackground(Color.GREEN);
                            labelsPatron[fila][columna].setBackground(Color.GREEN);
                        } else {
                            labelsResultado[fila][columna].setBackground(Color.RED);
                            labelsPatron[fila][columna].setBackground(Color.RED);
                        }
                    });

                    if (!celdaCoincide) {
                        coincide = false;
                        finalizarAnalisis(false);
                        return;
                    }

                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException e) {
                        return;
                    }
                }
            }

            finalizarAnalisis(coincide);
        });

        hilo.start();
    }
    
    private void finalizarAnalisis(boolean coincide) {
        SwingUtilities.invokeLater(() -> {
            investigadorFrame.recibirResultadoAnalisis(coincide, nombrePatron);
        });
    }
    
    public static void main(String args[]) {

        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AnalisisFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
