package vista;

import modelo.Investigador;
import modelo.Muestra;
import modelo.Patron;
import modelo.SistemaDatos;

/**
 *
 * @author danie
 */
public class InvestigadorFrame extends javax.swing.JFrame {
    
    private Investigador investigador;
    public void cargarCombos() {
        comboMuestra.removeAllItems();
        comboPatron.removeAllItems();

        for (Muestra m : SistemaDatos.muestras) {
            if (m.getCodigoInvestigadorAsignado().equals(investigador.getCodigo())
                    && m.getEstado().equals("En proceso")) {
                comboMuestra.addItem(m.getCodigo());
            }
        }

        for (Patron p : SistemaDatos.patrones) {
            comboPatron.addItem(p.getCodigo());
        }
    }
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InvestigadorFrame.class.getName());

    
    
    public InvestigadorFrame() {
        initComponents();
    }
    
    public InvestigadorFrame(Investigador investigador) {
        initComponents();
        this.investigador = investigador;
        setTitle("Panel Investigador - " + investigador.getNombre());
        cargarCombos();
        actualizarTablaResultados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboMuestra = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboPatron = new javax.swing.JComboBox<>();
        btnAnalizar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Muestra");

        jLabel2.setText("Patrón a analizar");

        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(this::btnAnalizarActionPerformed);

        lblResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblResultado.setText("Resultado: Pendiente");

        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAnalizar)
                        .addGap(397, 397, 397))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCerrarSesion)
                        .addGap(380, 380, 380))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboMuestra, 0, 110, Short.MAX_VALUE)
                            .addComponent(comboPatron, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(191, 191, 191))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPatron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(48, 48, 48)
                .addComponent(btnAnalizar)
                .addGap(50, 50, 50)
                .addComponent(lblResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(45, 45, 45))
        );

        jTabbedPane2.addTab("Análisis", jPanel1);

        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Muestra", "Patrón", "Fecha", "Hora", "Resultado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaResultados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Resultados", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        if (comboMuestra.getSelectedItem() == null || comboPatron.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione muestra y patrón");
            return;
        }

        String codigoMuestra = comboMuestra.getSelectedItem().toString();
        String codigoPatron = comboPatron.getSelectedItem().toString();

        Muestra muestra = null;
        Patron patron = null;

        for (Muestra m : SistemaDatos.muestras) {
            if (m.getCodigo().equals(codigoMuestra)) {
            muestra = m;
            break;
            }
        }

        for (Patron p : SistemaDatos.patrones) {
            if (p.getCodigo().equals(codigoPatron)) {
            patron = p;
            break;
            }
        }

        if (muestra == null || patron == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró muestra o patrón");
            return;
        }

        AnalisisFrame ventana = new AnalisisFrame(
            obtenerMatriz2x2(muestra.getMatriz()),
            obtenerMatriz2x2(patron.getMatriz()),
            this,
            patron.getNombre()
        );

        ventana.setVisible(true);
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        LoginFrame login = new LoginFrame();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    public void recibirResultadoAnalisis(boolean coincide, String nombrePatron) {
        String codigoMuestra = comboMuestra.getSelectedItem().toString();
        String codigoPatron = comboPatron.getSelectedItem().toString();

        String textoResultado;

        if (coincide) {
            textoResultado = "Coincide";
            lblResultado.setText("La muestra coincide con " + nombrePatron);
        } else {
            textoResultado = "No coincide";
            lblResultado.setText("La muestra no coincide con " + nombrePatron);
        }

        for (Muestra m : SistemaDatos.muestras) {
            if (m.getCodigo().equals(codigoMuestra)) {
                m.setEstado("Procesada");
                break;
            }
        }

        java.time.LocalDate fecha = java.time.LocalDate.now();
        java.time.LocalTime hora = java.time.LocalTime.now();

        int numero = SistemaDatos.resultados.size() + 1;

        modelo.Resultado nuevoResultado = new modelo.Resultado(
            numero,
            codigoMuestra,
            codigoPatron,
            fecha.toString(),
            hora.toString().substring(0, 8),
            textoResultado,
            investigador.getCodigo()
        );

        SistemaDatos.resultados.add(nuevoResultado);

        actualizarTablaResultados();
        cargarCombos();
        util.PersistenciaUtil.guardarDatos();
    }
    
    public void actualizarTablaResultados() {
    javax.swing.table.DefaultTableModel modeloTabla =
            (javax.swing.table.DefaultTableModel) tablaResultados.getModel();

    modeloTabla.setRowCount(0);

    for (modelo.Resultado r : SistemaDatos.resultados) {
        if (r.getCodigoInvestigador().equals(investigador.getCodigo())) {
            modeloTabla.addRow(new Object[]{
                r.getNumeroAnalisis(),
                r.getCodigoMuestra(),
                r.getCodigoPatron(),
                r.getFecha(),
                r.getHora(),
                r.getResultado()
            });
        }
    }
}
    
    public int[][] obtenerMatriz2x2(int[][] matriz) {
    if (matriz != null && matriz.length >= 2 && matriz[0].length >= 2) {
        return new int[][]{
            {matriz[0][0], matriz[0][1]},
            {matriz[1][0], matriz[1][1]}
        };
    }

    return new int[][]{
        {1, 0},
        {0, 1}
    };
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InvestigadorFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JComboBox<String> comboMuestra;
    private javax.swing.JComboBox<String> comboPatron;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTable tablaResultados;
    // End of variables declaration//GEN-END:variables
}
